# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '40 9 * * 1-5'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        pip install "cython<3.0.0" wheel
        pip install "pyyaml==5.4.1" --no-build-isolation
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run main.py
      run: |
           python3 main.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sequoia
        path: |
              logs/sequoia-＊.log
